### ISSUE TITLE
Help adding kernel support for dumpling = OP5T

### ISSUE THREAD

**Issue by Danfro** [DavidVentura/Wireguard_qml#30]
**What device do you have?**

**What is the output of `uname -a` on the device?**
`Linux ubuntu-phablet 4.4.153-lineage+ #1 SMP PREEMPT Sat Aug 19 00:05:49 CEST 2023 aarch64 aarch64 aarch64 GNU/Linux`

**Where is the kernel repo?**
I already reported it there as well:
https://gitlab.com/ubports/porting/community-ports/android9/oneplus-5/oneplus-cheeseburger-dumpling/-/issues/4

**Comment by JamiKettunen** [comment]
Afaik this should be done now, was there some other issue with the app still?

**Comment by Danfro** [comment]
You are right, this is done, your kernel patch does get detected fine. Thanks again. I forgot that I had this one open here too.

Although even with the patch the app does still fail to work properly on my OP5T. 
The connection is established, but I fail to reach devices in my homenetwork.
When connecting I get this error:

```
[30.03.24 20:25]  phablet : TTY=unknown ; PWD=/opt/click.ubuntu.com/wireguard.davidv.dev/1.0.0 ; USER=root ; COMMAND=/usr/bin/sed -i 1inameserver 192.168.178.1 /etc/resolv.conf
[30.03.24 20:25] pam_unix(sudo:session): session opened for user root by phablet(uid=0)
[30.03.24 20:25] sed: couldn't open temporary file /etc/sedqq0vgG: Read-only file system
[30.03.24 20:25] pam_unix(sudo:session): session closed for user root
```
Making the device r/w doesn't solve this issue.

Edit: when running the command in terminal, I get the error `/usr/bin/sed: can't read 192.168.178.1: No such file or directory`. So maybe something wrong with this sed command?

But I guess I should close this issue here and open a new one.
