### ISSUE TITLE
python: vpn.can_use_kernel_module() detection is buggy

### ISSUE THREAD

**Issue by fredldotme** [DavidVentura/Wireguard_qml#4]
After importing WireGuard into the Pixel 3a port I tried the WireGuard QML application, but the detection of kernel support is buggy.

`src/vpn.py/can_use_kernel_module()` detects the kernel support via a `sudo` command, though the users password is never requested, resulting in failure of the detection altogether.

Manually running its commands on the Pixel 3a allows the WireGuard link device to be created and deleted successfully, so I assume the app needs to request the users password similarly to what ISODrive does: https://github.com/fredldotme/ISODriveUT/blob/master/src/commandrunner.cpp

**Comment by luksus42** [comment]
It is the same issue on Fairphone 3.

**Comment by DavidVentura** [comment]
interesting; i don't have a sudo password and never set one, assumed it was the same for everyone on UT.
there is _plenty_ of sudo usage, i'll take a look at how other apps do this, but i think it will be somewhat challenging, as things like the daemon need sudo to update the routes on network change, etc

**Comment by Joshndroid** [comment]
@fredldotme Did you get this working?
